"""Initial

Revision ID: 46d35d631cb4
Revises: 
Create Date: 2025-08-24 01:08:27.980424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46d35d631cb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.String(length=10), nullable=False),
    sa.Column('major_id', sa.String(length=10), nullable=False),
    sa.Column('group_code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_code'], ['exam_groups.group_code'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admission_scores')
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('admission_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('major_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('group_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_code'], ['exam_groups.group_code'], name=op.f('admission_scores_group_code_fkey')),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], name=op.f('admission_scores_major_id_fkey')),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('admission_scores_university_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admission_scores_pkey'))
    )
    op.drop_table('admission_score')
    # ### end Alembic commands ###
